### ISSUE TITLE
Research how should SSHv2 protocol work

### ISSUE THREAD

**Issue by uncommon-nickname** [uncommon-nickname/parustiko#1]
https://www.openssh.com/specs.html

- RFC 4250 (assigned numbers)
Message frame https://datatracker.ietf.org/doc/html/rfc4250#section-4.1.1
Service names https://datatracker.ietf.org/doc/html/rfc4250#section-4.7
Auth methods names https://datatracker.ietf.org/doc/html/rfc4250#section-4.8
Connection protocol channel types https://datatracker.ietf.org/doc/html/rfc4250#section-4.9.1
Request names https://datatracker.ietf.org/doc/html/rfc4250#section-4.9.3
Encryption algorithms https://datatracker.ietf.org/doc/html/rfc4250#section-4.11

- RFC 4251 (Protocol architecture)
Data types https://datatracker.ietf.org/doc/html/rfc4251#section-5
None cipher is allowed only in DEBUG mode, on PROD there must be >=AES
TODO

-RFC 4254 (connection) - IMPORTANT!

**Comment by Leghart** [comment]
Diffie-Hellman algorithm

**Comment by uncommon-nickname** [comment]
![image](https://github.com/user-attachments/assets/0eab78a6-5d09-4e30-96af-90e83b5435f9)

**Comment by uncommon-nickname** [comment]
![image](https://github.com/user-attachments/assets/2421f64b-2bcc-4fc8-b9d7-e544c8de859f)

**Comment by uncommon-nickname** [comment]
![image](https://github.com/user-attachments/assets/10adb85f-3d33-4b88-becf-8af3524510b0)

**Comment by uncommon-nickname** [comment]
![image](https://github.com/user-attachments/assets/99ce38da-d3b3-46f0-8a6a-eb1c349ce7ac)
